# Generated by Django 5.1.2 on 2024-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_withdraw_from_address_withdraw_to_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='time_st_for_expired',
            field=models.IntegerField(default=1730990256),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='time_st_for_expired',
            field=models.IntegerField(default=1730990256),
        ),
    ]
