# Generated by Django 5.1.2 on 2024-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_deposit_time_st_for_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='tx_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='from_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='time_st_for_expired',
            field=models.IntegerField(default=1731081510),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='time_st_for_expired',
            field=models.IntegerField(default=1731081510),
        ),
    ]
