# Generated by Django 5.1.2 on 2024-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_withdraw_tx_id_alter_deposit_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='time_st_for_expired',
            field=models.IntegerField(default=1731088643),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='time_st_for_expired',
            field=models.IntegerField(default=1731088643),
        ),
    ]
