# Generated by Django 5.1.2 on 2024-10-21 15:42

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_ready1', models.BooleanField(default=False)),
                ('is_ready2', models.BooleanField(default=False)),
                ('dice1', models.IntegerField(blank=True, null=True)),
                ('dice2', models.IntegerField(blank=True, null=True)),
                ('last_move_time', models.DateTimeField(blank=True, null=True)),
                ('move_deadline', models.DateTimeField(blank=True, null=True)),
                ('move_history', models.JSONField(default=dict)),
                ('place_status', models.JSONField(default=dict)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game_Room',
                'verbose_name_plural': 'Game_Rooms',
                'db_table': 'game_rooms',
            },
        ),
        migrations.CreateModel(
            name='GameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='table_images/')),
                ('xp_for_winner', models.IntegerField()),
                ('xp_for_loser', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game_Table',
                'verbose_name_plural': 'Game_Tables',
            },
        ),
        migrations.CreateModel(
            name='PlayerWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Player_Warning',
                'verbose_name_plural': 'Player_Warnings',
                'db_table': 'player_warnings',
            },
        ),
        migrations.CreateModel(
            name='WaitingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=datetime.datetime(2024, 10, 21, 15, 44, 21, 337714, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Waiting_Room',
                'verbose_name_plural': 'Waiting_Rooms',
                'db_table': 'waiting_rooms',
            },
        ),
    ]
