# Generated by Django 5.1.2 on 2024-10-21 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 17, 0, 36, 704800, tzinfo=datetime.timezone.utc)),
        ),
    ]
