# Generated by Django 5.1.2 on 2024-10-21 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0008_alter_gameroom_current_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='turn_tas_player_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='turn_tas_player_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 21, 24, 28, 533633, tzinfo=datetime.timezone.utc)),
        ),
    ]
