# Generated by Django 5.1.2 on 2024-10-27 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0010_gameroom_game_is_started_alter_waitingroom_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 18, 58, 4, 911248, tzinfo=datetime.timezone.utc)),
        ),
    ]
