# Generated by Django 5.1.2 on 2024-10-29 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0011_alter_waitingroom_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='last_move_time',
            new_name='time_player_1',
        ),
        migrations.RenameField(
            model_name='gameroom',
            old_name='move_deadline',
            new_name='time_player_2',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='is_player_1_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='is_player_2_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='place_status',
            field=models.JSONField(blank=True, default={'p0': [], 'p1': [1, 1], 'p10': [], 'p11': [], 'p12': [1, 1, 1, 1, 1], 'p13': [2, 2, 2, 2, 2], 'p14': [], 'p15': [], 'p16': [], 'p17': [1, 1, 1], 'p18': [], 'p19': [1, 1, 1, 1, 1], 'p2': [], 'p20': [], 'p21': [], 'p22': [], 'p23': [], 'p24': [2, 2], 'p3': [], 'p4': [], 'p5': [], 'p6': [2, 2, 2, 2, 2], 'p7': [], 'p8': [2, 2, 2], 'p9': []}, null=True),
        ),
        migrations.AlterField(
            model_name='gametable',
            name='image',
            field=models.ImageField(default=1, upload_to='table_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 19, 8, 22, 667976, tzinfo=datetime.timezone.utc)),
        ),
    ]
