# Generated by Django 5.1.2 on 2024-10-29 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0012_rename_last_move_time_gameroom_time_player_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='time_player_1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='time_player_2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 19, 12, 30, 528499, tzinfo=datetime.timezone.utc)),
        ),
    ]
