# Generated by Django 5.1.2 on 2024-10-29 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0013_alter_gameroom_time_player_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_polling_time',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 19, 22, 59, 141169, tzinfo=datetime.timezone.utc)),
        ),
    ]
