# Generated by Django 5.1.2 on 2024-10-30 18:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0015_alter_gameroom_time_player_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerwarning',
            options={'verbose_name': 'Player_Warning_backgammon', 'verbose_name_plural': 'Player_Warnings_backgammon'},
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 18, 27, 55, 265429, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BackgammonPlayerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_match', models.IntegerField(default=0)),
                ('total_win', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
