# Generated by Django 5.1.2 on 2024-10-30 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0016_alter_playerwarning_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='percent_for_winner',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 19, 5, 45, 786859, tzinfo=datetime.timezone.utc)),
        ),
    ]
