# Generated by Django 5.1.2 on 2024-10-31 12:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0017_gametable_percent_for_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='table',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='back_game.gametable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 12, 16, 30, 256141, tzinfo=datetime.timezone.utc)),
        ),
    ]
