# Generated by Django 5.1.2 on 2024-10-31 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0019_remove_gameroom_waiting_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_turn_time',
            field=models.FloatField(blank=True, default=45, null=True),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 14, 4, 13, 914958, tzinfo=datetime.timezone.utc)),
        ),
    ]
