# Generated by Django 5.1.2 on 2024-10-31 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0020_gameroom_game_turn_time_alter_waitingroom_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_room_is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 31, 18, 23, 51, 320684, tzinfo=datetime.timezone.utc)),
        ),
    ]
