# Generated by Django 5.1.2 on 2024-11-01 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0027_alter_waitingroom_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 8, 40, 3, 115112, tzinfo=datetime.timezone.utc)),
        ),
    ]
