# Generated by Django 5.1.2 on 2024-11-01 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0029_alter_waitingroom_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 1, 11, 23, 3, 234155, tzinfo=datetime.timezone.utc)),
        ),
    ]
