# Generated by Django 5.1.2 on 2024-11-03 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0030_gameroom_game_start_time_alter_waitingroom_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_player_1_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='is_player_2_win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 7, 8, 18, 300291, tzinfo=datetime.timezone.utc)),
        ),
    ]
