# Generated by Django 5.1.2 on 2024-11-03 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0031_gameroom_is_player_1_win_gameroom_is_player_2_win_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 10, 11, 36, 999027, tzinfo=datetime.timezone.utc)),
        ),
    ]
