# Generated by Django 5.1.2 on 2024-11-03 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0032_alter_waitingroom_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='percent_for_left_user_winner',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 11, 3, 54, 260472, tzinfo=datetime.timezone.utc)),
        ),
    ]
