# Generated by Django 5.1.2 on 2024-11-06 21:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_game', '0036_alter_gameroom_game_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='game_start_time',
            field=models.IntegerField(blank=True, default=1730929385, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_game.gametable'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='time_player_1',
            field=models.IntegerField(blank=True, default=1730929385, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='time_player_2',
            field=models.IntegerField(blank=True, default=1730929385, null=True),
        ),
        migrations.AlterField(
            model_name='waitingroom',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 6, 21, 45, 5, 824152, tzinfo=datetime.timezone.utc)),
        ),
    ]
