# Generated by Django 5.1.2 on 2024-10-21 17:04

import players.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_user_managers_user_email_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', players.models.UserManager()),
            ],
        ),
    ]
