# Generated by Django 5.1.2 on 2024-10-21 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
