# Generated by Django 5.1.2 on 2024-10-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=222, max_length=128, verbose_name='Tel_ID'),
            preserve_default=False,
        ),
    ]
