# Generated by Django 5.1.2 on 2024-10-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_token',
            field=models.FloatField(default=0, verbose_name='game token'),
        ),
    ]
