# Generated by Django 5.1.2 on 2024-11-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_profit',
            field=models.FloatField(default=0, verbose_name='referral profit token'),
        ),
    ]
