# Generated by Django 5.1.2 on 2024-11-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_user_referral_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backgammon_game_wins',
            field=models.IntegerField(default=0),
        ),
    ]
