# Generated by Django 5.1.2 on 2024-11-08 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_user_backgammon_game_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeReferralsProfitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('claim_time', models.DateTimeField(auto_now_add=True)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
