# Generated by Django 5.1.2 on 2024-11-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0018_alter_user_avatar_logincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincode',
            name='code',
            field=models.CharField(default=887510, max_length=20),
        ),
        migrations.AlterField(
            model_name='logincode',
            name='time_st',
            field=models.CharField(default=1732655939, max_length=120),
        ),
    ]
